apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: mini-cloud
  labels:
    project: k8s-mini-cloud
    component: mysql
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-static
  volumeName: pv-mysql-nfs