apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mini-cloud
  labels:
    project: k8s-mini-cloud
    component: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysql
