apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"my-ip-pool","namespace":"metallb-system"},"spec":{"addresses":["10.10.8.200-10.10.8.210"],"autoAssign":true}}
    creationTimestamp: "2026-03-03T08:00:23Z"
    generation: 1
    name: my-ip-pool
    namespace: metallb-system
    resourceVersion: "697818"
    uid: 197bf8c9-f6af-4d88-929c-b9c8a2e438d4
  spec:
    addresses:
    - 10.10.8.200-10.10.8.210
    autoAssign: true
    avoidBuggyIPs: false
kind: List
metadata:
  resourceVersion: ""
