apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wp-nfs
  labels:
    project: k8s-mini-cloud
    component: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/wordpress
    server: 10.10.8.100
