apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wp
  namespace: mini-cloud
  labels:
    project: k8s-mini-cloud
    component: wordpress
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  volumeName: pv-wp-nfs
