apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: mini-cloud 
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh","-c","echo hello-$(date) > /data/ok.txt && cat /data/ok.txt && sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-wp